# Действия которые можно использовать:

# Написать игроку -  tell: сообщение
# Выполнить команду через консоль - console: команда
# Выполнить команду от игрока player:
# Закрыть меню - closemenu

# Чтобы Открыть/Закрыть меню используйте shift+F
# Для версий 1.1 и ниже
# Ограничения на количество букв в меню - 13
# Поддержка только русских букв (все неизвестные буквы заменяются на пробелы)



menu:
  spawn:
    name: спавн
    actions:
      - closemenu
      - tell: поздравляем, вы телепортированы на спавн
  day:
    name: день
    actions:
      - console: time set day
      - tell: Время день
  night:
    name: ночь
    actions:
      - console: time set night
      - tell: Время ночь
  home:
    name: домой
    actions:
      - closemenu
      - tell: Дом милый дом
  hello:
    name: привет
    actions:
      - closemenu
      - tell: привет %player_name%
  buy:
    name: пока
    actions:
      - closemenu
      - tell: пока %player_name%

