#Menu open on action "shift + F"
# permissions to open rpgmenu.use
MainMenu: mainmenu

# do not touch these settings if you do not know what you are doing
settings:
  # position of menu
  menupos: -600
  charlength: 7
  menulength: 140


Resoursepack:

  # Define your Direct-Download-Link to your Resource Pack
  download-link: https://www.dropbox.com/s/ce9sh5cwn0t63w5/rpgmenu.zip?dl=1

  #download resource pack at join or no
  download-when-join: true

  #kick the player if he has not downloaded the resource
  kick-on-deny: true
