# Действия которые можно использовать:
#
# Написать игроку -  tell: сообщение
# Выполнить команду через консоль - console: команда
# Выполнить команду от игрока - player: команда
# Закрыть меню - closemenu: 1
# Открыть другое меню - openmenu: <имя меню>
#
# Чтобы Открыть/Закрыть меню используйте shift+F
#
# Для версий 1.3
# Ограничения на количество букв в меню - 13
# Поддержка поддержка русских и английских букв (все неизвестные буквы заменяются на пробелы)
MainMenu: mainmenu
