name: MenuRpg
version: ${project.version}
main: main.menurpg.MenuRPGPlugin
api-version: 1.16
authors: [ rain_chat ]
softdepend: [PlaceholderAPI]
commands:
  rpgmenu:
    description: "use /rpgmenu"
  rpgresourse:
